# Generated by Django 5.1.2 on 2025-07-23 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('road', models.CharField(max_length=100, verbose_name='rua')),
                ('number', models.PositiveIntegerField(verbose_name='numero da casa')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='FisicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='Cadastro de Pessoa Fisica - CPF')),
                ('rg', models.CharField(max_length=100, verbose_name='Registro Geral - RG')),
                ('dateOfBirth', models.CharField(max_length=14, verbose_name='Data de Aniversario')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foreigner', models.CharField(max_length=100, verbose_name='Nome')),
                ('num_foreigner', models.CharField(max_length=100, verbose_name='Numero do Documento')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkPhone', models.CharField(max_length=100, verbose_name='Telefone de Trabalho')),
                ('PersonalPhone', models.CharField(max_length=100, verbose_name='Telefone Pessoal')),
                ('isActive', models.BooleanField(max_length=100, verbose_name='isActive')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='site')),
                ('salesman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('creditLimit', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=100, verbose_name='Limite de Crédito')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='E-mail')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha')),
                ('isClient', models.BooleanField(blank=True, null=True, verbose_name='Cliente')),
                ('isSupllier', models.BooleanField(blank=True, null=True, verbose_name='Fornecedor')),
                ('isUser', models.BooleanField(blank=True, null=True, verbose_name='Usuario do Sistema')),
                ('isEmployee', models.BooleanField(blank=True, null=True, verbose_name='Funcionario')),
                ('issalesman', models.BooleanField(blank=True, null=True, verbose_name='Vendedor')),
                ('isFormer_employee', models.BooleanField(blank=True, null=True, verbose_name='Ex-Funcionario')),
                ('isCarrier', models.BooleanField(blank=True, null=True, verbose_name='Transportadora')),
                ('isDelivery_man', models.BooleanField(blank=True, null=True, verbose_name='Entregador')),
                ('isTechnician', models.BooleanField(blank=True, null=True, verbose_name='Tecnico')),
                ('id_FisicPerson_fk', models.OneToOneField(blank=True, db_column='id_FisicPerson_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.fisicperson')),
                ('id_ForeignPerson_fk', models.OneToOneField(blank=True, db_column='id_ForeignPerson_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.foreignperson')),
                ('id_LegalPerson_fk', models.OneToOneField(blank=True, db_column='id_LegalPerson_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.legalperson')),
                ('id_address_fk', models.OneToOneField(db_column='id_address_fk', on_delete=django.db.models.deletion.CASCADE, to='registry.address')),
                ('id_user_fk', models.OneToOneField(blank=True, db_column='id_user_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_data', models.DateTimeField(verbose_name='Data do Crédito')),
                ('credit_value', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.person', verbose_name='pessoa_creditada')),
            ],
        ),
    ]
