# Generated by Django 5.1.2 on 2024-12-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('road', models.CharField(max_length=100, verbose_name='rua')),
                ('number', models.PositiveIntegerField(verbose_name='numero da casa')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='FisicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='Cadastro de Pessoa Fisica - CPF')),
                ('rg', models.CharField(max_length=100, verbose_name='Registro Geral - RG')),
                ('dateOfBirth', models.CharField(max_length=14, verbose_name='Data de Aniversario')),
                ('id_address_fk', models.OneToOneField(db_column='id_address_fk', on_delete=django.db.models.deletion.CASCADE, to='Registry.address')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foreigner', models.CharField(max_length=100, verbose_name='Nome')),
                ('num_foreigner', models.CharField(max_length=100, verbose_name='Numero do Documento')),
                ('id_address_fk', models.OneToOneField(db_column='id_address_fk', on_delete=django.db.models.deletion.CASCADE, to='Registry.address')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('id_address_fk', models.OneToOneField(db_column='id_address_fk', on_delete=django.db.models.deletion.CASCADE, to='Registry.address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkPhone', models.CharField(max_length=100, verbose_name='WorkPhone')),
                ('PersonalPhone', models.CharField(max_length=100, verbose_name='PersonalPhone')),
                ('isActive', models.BooleanField(max_length=100, verbose_name='isActive')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='site')),
                ('salesman', models.CharField(blank=True, max_length=100, null=True, verbose_name='salesman')),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=10, max_length=100, verbose_name='creditLimit')),
                ('isClient', models.BooleanField(verbose_name='É Cliente')),
                ('isSupllier', models.BooleanField(verbose_name='É Fornecedor')),
                ('isUser', models.BooleanField(verbose_name='É Usuario do Sistema')),
                ('isEmployee', models.BooleanField(verbose_name='É Funcionario')),
                ('isFormer_employee', models.BooleanField(verbose_name='É Ex-Funcionario')),
                ('isCarrier', models.BooleanField(verbose_name='É Transportadora')),
                ('isDelivery_man', models.BooleanField(verbose_name='É Entregador')),
                ('isTechnician', models.BooleanField(verbose_name='É Tecnico')),
                ('id_FisicPerson_fk', models.OneToOneField(blank=True, db_column='id_FisicPerson_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.fisicperson')),
                ('id_ForeignPerson_fk', models.OneToOneField(blank=True, db_column='id_ForeignPerson_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.foreignperson')),
                ('id_LegalPerson_fk', models.OneToOneField(blank=True, db_column='id_LegalPerson_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.legalperson')),
            ],
        ),
    ]
