# Generated by Django 5.1.2 on 2025-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isSalesman',
            field=models.BooleanField(default=True, verbose_name='É Vendedor'),
        ),
    ]
