# Generated by Django 5.1.2 on 2024-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='creditLimit',
            field=models.PositiveIntegerField(max_length=100, verbose_name='creditLimit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salesman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='salesman'),
        ),
        migrations.AlterField(
            model_name='person',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='site'),
        ),
    ]
