# Generated by Django 5.1.2 on 2025-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isCarrier',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isClient',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isDelivery_man',
            field=models.BooleanField(blank=True, null=True, verbose_name='Entregador'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isEmployee',
            field=models.BooleanField(blank=True, null=True, verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isFormer_employee',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ex-Funcionario'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isSalesman',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isSupllier',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isTechnician',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tecnico'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isUser',
            field=models.BooleanField(blank=True, null=True, verbose_name='Usuario do Sistema'),
        ),
    ]
