# Generated by Django 5.1.2 on 2025-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0003_alter_person_issalesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isCarrier',
            field=models.BooleanField(verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isClient',
            field=models.BooleanField(verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isDelivery_man',
            field=models.BooleanField(verbose_name='Entregador'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isEmployee',
            field=models.BooleanField(verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isFormer_employee',
            field=models.BooleanField(verbose_name='Ex-Funcionario'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isSalesman',
            field=models.BooleanField(verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isSupllier',
            field=models.BooleanField(verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isTechnician',
            field=models.BooleanField(verbose_name='Tecnico'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isUser',
            field=models.BooleanField(verbose_name='Usuario do Sistema'),
        ),
    ]
