# Generated by Django 5.1.2 on 2025-01-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registry', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.PositiveIntegerField(verbose_name='Numero do Documento')),
                ('date_account', models.DateTimeField(verbose_name='Data da Conta')),
                ('numberOfInstallments', models.PositiveIntegerField(verbose_name='Numero de Parcelas')),
                ('installment_Range', models.CharField(blank=True, choices=[('15', 'A cada 15 dias'), ('20', 'A cada 20 dias'), ('23', 'A cada 23 dias'), ('28', 'A cada 28 dias'), ('30', 'A cada 30 dias')], default='este mês', max_length=20, null=True, verbose_name='Intervalo de Parcelas')),
                ('date_init', models.DateTimeField(verbose_name='Data de Inicio')),
                ('valueOfInstallments', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Parcelas')),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('peopleWatching', models.TextField(blank=True, null=True, verbose_name='Observações para a Pessoas')),
                ('systemWatching', models.TextField(blank=True, null=True, verbose_name='Observações para o Sistema')),
                ('chartOfAccounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.chartofaccounts', verbose_name='Plano de Contas')),
                ('pessoa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registry.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.PositiveIntegerField(verbose_name='Numero do Documento')),
                ('data_da_conta', models.DateTimeField(verbose_name='Data da Conta a Pagar')),
                ('numberOfInstallments', models.PositiveIntegerField(verbose_name='Numero de Parcelas')),
                ('valueOfInstallments', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Numero de Parcelas')),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('peopleWatching', models.TextField(blank=True, null=True, verbose_name='Observações para a Pessoas')),
                ('systemWatching', models.TextField(blank=True, null=True, verbose_name='Observações para o Sistema')),
                ('chartOfAccounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.chartofaccounts', verbose_name='Plano de Contas')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registry.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.DateField(max_length=50, verbose_name='Dias')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('interestType', models.CharField(blank=True, choices=[('percent', '(%)'), ('value', '(R$)')], default='percent', max_length=10, null=True, verbose_name='Tipo de Juros')),
                ('interestPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Juros (%)')),
                ('interestValue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='juros R$')),
                ('fineType', models.CharField(blank=True, choices=[('percent', '(%)'), ('value', '(R$)')], default='percent', max_length=10, null=True, verbose_name='Tipo de Multa')),
                ('finePercent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='multa (%)')),
                ('fineValue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='multa R$')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accountspayable', verbose_name='id_AccountsPayable')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.DateField(max_length=50, verbose_name='Dias')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('interestPercent', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Juros (%)')),
                ('interestValue', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='juros R$')),
                ('finePercent', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='multa (%)')),
                ('fineValue', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='multa R$')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accountsreceivable', verbose_name='id_AccountsReceivable')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
            ],
        ),
    ]
