# Generated by Django 5.1.2 on 2025-05-16 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registry', '0001_initial'),
        ('Sale', '0001_initial'),
        ('Service', '0001_initial'),
        ('config', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição da Conta')),
                ('documentNumber', models.PositiveIntegerField(verbose_name='Numero do Documento')),
                ('date_account', models.DateField(verbose_name='Data da Conta')),
                ('numberOfInstallments', models.PositiveIntegerField(verbose_name='Numero de Parcelas')),
                ('installment_Range', models.CharField(blank=True, choices=[('15', 'A cada 15 dias'), ('20', 'A cada 20 dias'), ('23', 'A cada 23 dias'), ('28', 'A cada 28 dias'), ('30', 'A cada 30 dias')], default='este mês', max_length=20, null=True, verbose_name='Intervalo de Parcelas')),
                ('date_init', models.DateField(verbose_name='Data de Inicio')),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('peopleWatching', models.TextField(blank=True, null=True, verbose_name='Observações para a Pessoas')),
                ('systemWatching', models.TextField(blank=True, null=True, verbose_name='Observações para o Sistema')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está Ativo')),
                ('chartOfAccounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.chartofaccounts', verbose_name='Plano de Contas')),
                ('pessoa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registry.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('closed_in', models.DateTimeField(auto_now_add=True, verbose_name='fechado_em')),
                ('caixa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.caixadiario')),
            ],
        ),
        migrations.CreateModel(
            name='Freight_PaymentMethod_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(blank=True, max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.IntegerField(blank=True, verbose_name='Dias')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('acc', models.BooleanField(verbose_name='Tipo de Conta')),
                ('activeCredit', models.BooleanField(blank=True, default=False)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.compra', verbose_name='id_compra')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(blank=True, max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.IntegerField(blank=True, verbose_name='Dias')),
                ('value_old', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Conta:')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('interestType', models.CharField(blank=True, choices=[('percent', '(%)'), ('value', '(R$)')], default='value', max_length=10, null=True, verbose_name='Tipo de Juros')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='juros')),
                ('fineType', models.CharField(blank=True, choices=[('percent', '(%)'), ('value', '(R$)')], default='value', max_length=10, null=True, verbose_name='Tipo de Multa')),
                ('fine', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Multa R$')),
                ('acc', models.BooleanField(verbose_name='Tipo de Conta')),
                ('activeCredit', models.BooleanField(blank=True, default=False)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.compra', verbose_name='id_compra')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accounts', verbose_name='id_Accounts')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='Forma de Pagamento')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service.vendaservice', verbose_name='id_vendaservico')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sale.venda', verbose_name='id_venda')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='finance.caixadiario')),
                ('forma_pagamento', models.ForeignKey(max_length=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod')),
                ('accounts_in_cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='finance.paymentmethod_accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Romaneio_PaymentMethod_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(blank=True, max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.IntegerField(blank=True, verbose_name='Dias')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('acc', models.BooleanField(verbose_name='Tipo de Conta')),
                ('activeCredit', models.BooleanField(blank=True, default=False)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.compra', verbose_name='id_compra')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tax_PaymentMethod_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField(blank=True, max_length=50, verbose_name='Data de Vencimento')),
                ('days', models.IntegerField(blank=True, verbose_name='Dias')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('acc', models.BooleanField(verbose_name='Tipo de Conta')),
                ('activeCredit', models.BooleanField(blank=True, default=False)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.compra', verbose_name='id_compra')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
        ),
    ]
