# Generated by Django 5.1.2 on 2025-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod_accounts',
            name='days',
            field=models.IntegerField(max_length=50, verbose_name='Dias'),
        ),
    ]
