# Generated by Django 5.1.2 on 2025-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='date_account',
            field=models.DateTimeField(verbose_name='Data da Conta'),
        ),
        migrations.AlterField(
            model_name='accountspayable',
            name='installment_Range',
            field=models.CharField(blank=True, choices=[('A cada 15 dias', 'A cada 15 dias'), ('A cada 20 dias', 'A cada 20 dias'), ('A cada 23 dias', 'A cada 23 dias'), ('A cada 28 dias', 'A cada 28 dias'), ('A cada 30 dias', 'A cada 30 dias')], default='este mês', max_length=20, null=True, verbose_name='Intervalo de Parcelas'),
        ),
        migrations.AlterField(
            model_name='accountspayable',
            name='valueOfInstallments',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Parcelas'),
        ),
        migrations.AlterField(
            model_name='paymentmethod_accountspayable',
            name='finePercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='multa (%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod_accountspayable',
            name='fineValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='multa R$'),
        ),
        migrations.AlterField(
            model_name='paymentmethod_accountspayable',
            name='interestPercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Juros (%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod_accountspayable',
            name='interestValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='juros R$'),
        ),
    ]
