# Generated by Django 5.1.2 on 2025-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='acc',
        ),
        migrations.AddField(
            model_name='paymentmethod_accounts',
            name='acc',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tipo de Conta'),
        ),
    ]
