# Generated by Django 5.1.2 on 2025-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_paymentmethod_accounts_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
