# Generated by Django 5.1.2 on 2025-01-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_accounts_acc_paymentmethod_accounts_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod_accounts',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.accounts', verbose_name='id_Accounts'),
        ),
    ]
