# Generated by Django 5.1.2 on 2025-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_da_compra',
            field=models.DateTimeField(verbose_name='Data da Compra'),
        ),
    ]
