# Generated by Django 5.1.2 on 2025-01-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraitem',
            old_name='discount_percentage',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='compraitem',
            old_name='total_value',
            new_name='price_total',
        ),
    ]
