# Generated by Django 5.1.2 on 2025-03-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registry', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Service', models.CharField(max_length=500, verbose_name='Nome do Serviço')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
                ('value_Service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='VendaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_venda', models.DateTimeField(verbose_name='Data da Venda')),
                ('observacao_pessoas', models.TextField(blank=True, null=True, verbose_name='Observações sobre as Pessoas')),
                ('observacao_sistema', models.TextField(blank=True, null=True, verbose_name='Observações do Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('product_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Produtos')),
                ('discount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Descontos de Produtos')),
                ('service_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Servicos')),
                ('discount_total_service', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Descontos')),
                ('total_value_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendaService', to='Registry.person', verbose_name='Pessoa')),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendaService', to='config.situation', verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='VendaItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto(%)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service', verbose_name='Servico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.vendaservice', verbose_name='vendaService')),
            ],
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto(%)')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.vendaservice', verbose_name='vendaProduct')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_VendaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.CharField(max_length=50, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service.vendaservice', verbose_name='id_vendaService')),
            ],
        ),
    ]
