# Generated by Django 5.1.2 on 2024-11-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=100, verbose_name='rua')),
                ('number', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='numero da casa')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('reference', models.CharField(max_length=100, verbose_name='Ponto de Referencia')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_paymentMethod', models.CharField(max_length=50, verbose_name='Nome da Forma de Pagamento')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('PersonalPhone', models.CharField(max_length=100, verbose_name='PersonalPhone')),
                ('isActive', models.BooleanField(max_length=100, verbose_name='isActive')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=25, verbose_name='Nome do Cargo')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Situation', models.CharField(max_length=50, verbose_name='Nome da Situação')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='FisicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='Cadastro de Pessoa Fisica - CPF')),
                ('rg', models.CharField(max_length=100, verbose_name='Registro Geral - RG')),
                ('dateOfBirth', models.DateField(max_length=100, verbose_name='Data de Aniversario')),
                ('id_address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foreigner', models.CharField(max_length=100, verbose_name='Nome')),
                ('num_foreigner', models.CharField(max_length=100, verbose_name='Numero do Documento')),
                ('id_address_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('id_address_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
    ]
