# Generated by Django 5.1.2 on 2024-11-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('road', models.CharField(max_length=100, verbose_name='rua')),
                ('number', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='numero da casa')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('reference', models.CharField(max_length=100, verbose_name='Ponto de Referencia')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_compra', models.CharField(max_length=10, verbose_name='Data da Compra')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_paymentMethod', models.CharField(max_length=50, verbose_name='Nome da Forma de Pagamento')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('PersonalPhone', models.CharField(max_length=100, verbose_name='PersonalPhone')),
                ('isActive', models.BooleanField(max_length=100, verbose_name='isActive')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=25, verbose_name='Nome do Cargo')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Situation', models.CharField(max_length=50, verbose_name='Nome da Situação')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='FisicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='Cadastro de Pessoa Fisica - CPF')),
                ('rg', models.CharField(max_length=100, verbose_name='Registro Geral - RG')),
                ('dateOfBirth', models.CharField(max_length=14, verbose_name='Data de Aniversario')),
                ('id_address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_pessoal', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Pessoal')),
                ('telefone_trabalho', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de Trabalho')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite de Crédito')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.address', verbose_name='Endereço')),
                ('pessoa_fisica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.fisicperson', verbose_name='Pessoa Física')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foreigner', models.CharField(max_length=100, verbose_name='Nome')),
                ('num_foreigner', models.CharField(max_length=100, verbose_name='Numero do Documento')),
                ('id_address_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('socialReason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('StateRegistration', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('typeOfTaxpayer', models.CharField(max_length=100, verbose_name='Tipo de Contribuinte')),
                ('MunicipalRegistration', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(max_length=100, verbose_name='SUFRAMA')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('id_address_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.address')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.CharField(max_length=50, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.compra', verbose_name='id_compra')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.person', verbose_name='Fornecedor'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('product_code', models.CharField(max_length=100, verbose_name='Código do Produto')),
                ('barcode', models.CharField(max_length=100, verbose_name='Código de Barras')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('cost_of_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo do Produto')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('ncm', models.CharField(max_length=10, verbose_name='NCM')),
                ('csosn', models.CharField(max_length=5, verbose_name='CSOSN')),
                ('cfop', models.CharField(max_length=7, verbose_name='CFOP')),
                ('current_quantity', models.IntegerField(verbose_name='Quantidade Atual')),
                ('maximum_quantity', models.IntegerField(verbose_name='Quantidade Máxima')),
                ('minimum_quantity', models.IntegerField(verbose_name='Quantidade Mínima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.person', verbose_name='Fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.situation', verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_venda', models.DateTimeField(verbose_name='Data da Venda')),
                ('observacao_pessoas', models.TextField(blank=True, null=True, verbose_name='Observações sobre as Pessoas')),
                ('observacao_sistema', models.TextField(blank=True, null=True, verbose_name='Observações do Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='config.client', verbose_name='Pessoa')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='config.situation', verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.CharField(max_length=50, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.venda', verbose_name='id_venda')),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.product', verbose_name='Produto')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.venda', verbose_name='Venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.product', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.venda', verbose_name='Venda')),
            ],
        ),
    ]
