# Generated by Django 5.1.2 on 2025-07-06 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_paymentMethod', models.CharField(max_length=50, verbose_name='Nome da Forma de Pagamento')),
                ('creditPermission', models.BooleanField(default=False, verbose_name='creditPermission')),
                ('considerInCash', models.BooleanField(blank=True, default=False, null=True, verbose_name='considerar em caixa')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=25, verbose_name='Nome do Cargo')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=500, verbose_name='Nome do Serviço')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
                ('value_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Situation', models.CharField(max_length=50, verbose_name='Nome da Situação')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codigo de Conta')),
                ('name_ChartOfAccounts', models.CharField(max_length=50, verbose_name='Nome do Plano de Contas')),
                ('natureOfTheAccount', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1, verbose_name='Natureza da Conta')),
                ('is_Active', models.BooleanField(default=True, verbose_name='ativo')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='config.chartofaccounts', verbose_name='Referente a')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='data e hora do log')),
                ('type', models.CharField(choices=[('08', 'formas de pagamento'), ('12', 'Login'), ('01', 'pessoa'), ('06', 'contas a pagar'), ('11', 'serviços'), ('02', 'produtos'), ('10', 'plano de contas'), ('04', 'vendas'), ('03', 'compras'), ('05', 'ordem de serviço'), ('07', 'contas a receber'), ('09', 'situação'), ('13', 'logout')], max_length=2, verbose_name='tipo de transação')),
                ('action', models.CharField(choices=[('e', 'login'), ('d', 'delete'), ('r', 'read'), ('u', 'update'), ('c', 'create'), ('s', 'logout')], max_length=1, verbose_name='tipo de transação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Info_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_old', models.CharField(max_length=255, verbose_name='Informação antiga')),
                ('info_now', models.CharField(max_length=255, null=True, verbose_name='Informação atual')),
                ('field', models.CharField(max_length=255, null=True, verbose_name='nome do campo')),
                ('log_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.log', verbose_name='log principal')),
            ],
        ),
        migrations.CreateModel(
            name='SuperGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome do super grupo')),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos que este super grupo engloba.', to='auth.group', verbose_name='grupos contidos')),
                ('members', models.ManyToManyField(blank=True, help_text='Usuários que pertencem a este super grupo.', related_name='super_groups', to=settings.AUTH_USER_MODEL, verbose_name='membros')),
            ],
            options={
                'verbose_name': 'super grupo',
                'verbose_name_plural': 'super grupos',
            },
        ),
    ]
