# Generated by Django 5.1.2 on 2024-11-13 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod_Purchase',
            new_name='PaymentMethod_Compra',
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.compra', verbose_name='Compra'),
        ),
    ]
