# Generated by Django 5.1.2 on 2025-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ChartOfAccounts', models.CharField(max_length=50, verbose_name='Nome do Plano de Contas')),
                ('is_Active', models.BooleanField(verbose_name='ativo')),
            ],
        ),
    ]
