# Generated by Django 5.1.2 on 2024-11-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('cost_of_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncm', models.CharField(max_length=10)),
                ('csosn', models.CharField(max_length=5)),
                ('cfop', models.CharField(max_length=7)),
                ('current_quantity', models.IntegerField()),
                ('maximum_quantity', models.IntegerField()),
                ('minimum_quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.person')),
            ],
        ),
    ]
