# Generated by Django 5.1.2 on 2024-11-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_fisicperson_dateofbirth_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaitem',
            name='total',
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePurchase', models.CharField(max_length=10, verbose_name='Data da Compra')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('id_Situation_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.situation', verbose_name='Situação')),
                ('id_fornecedor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.person', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.CharField(max_length=50, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.purchase', verbose_name='id_compra')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.venda', verbose_name='Venda')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.product', verbose_name='Produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
