# Generated by Django 5.1.2 on 2025-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_chartofaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_Active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
