# Generated by Django 5.1.2 on 2024-11-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
        ('config', '0002_rename_paymentmethod_purchase_paymentmethod_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisicperson',
            name='id_address_fk',
        ),
        migrations.AlterField(
            model_name='client',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.address', verbose_name='Endereço'),
        ),
        migrations.RemoveField(
            model_name='foreignperson',
            name='id_address_fk',
        ),
        migrations.AlterField(
            model_name='client',
            name='pessoa_fisica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registry.fisicperson', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registry.person', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.person', verbose_name='Fornecedor'),
        ),
        migrations.DeleteModel(
            name='LegalPerson',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ForeignPerson',
        ),
        migrations.DeleteModel(
            name='FisicPerson',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
