# Generated by Django 5.1.2 on 2025-06-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('purchase', '0001_initial'),
        ('registry', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_venda', models.DateTimeField(verbose_name='Data da Venda')),
                ('observacao_pessoas', models.TextField(blank=True, null=True, verbose_name='Observações sobre as Pessoas')),
                ('observacao_sistema', models.TextField(blank=True, null=True, verbose_name='Observações do Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('product_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Produtos')),
                ('discount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Descontos')),
                ('apply_credit', models.BooleanField(default=False, verbose_name='Crédito Aplicado')),
                ('value_apply_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor do Crédito Aplicado')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.person', verbose_name='Pessoa')),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='config.situation', verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.CharField(max_length=50, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago:')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='id_forma_de_pagamento')),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.venda', verbose_name='id_venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Produto')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade atual de Produtos')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto(%)')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VendaProduto', to='purchase.product', verbose_name='Produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vendaservice', verbose_name='Ordem de Serviço')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.venda', verbose_name='Venda')),
            ],
        ),
    ]
