# Generated by Django 5.1.2 on 2025-01-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sale', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sale.venda', verbose_name='Venda'),
        ),
    ]
