# Generated by Django 5.1.2 on 2025-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
        migrations.AddField(
            model_name='venda',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Descontos'),
        ),
        migrations.AddField(
            model_name='venda',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Produtos'),
        ),
        migrations.AddField(
            model_name='venda',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
