# Generated by Django 5.1.2 on 2025-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0003_remove_venda_total_venda_discount_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Descontos'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='product_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Produtos'),
        ),
    ]
