# Generated by Django 5.1.2 on 2025-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0004_alter_venda_discount_total_alter_venda_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaitem',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
